jespertheend/splix

- gameServer/src/WebSocketConnection.js
- gameServer/src/config.js
- gameServer/src/gameplay/Arena.js
- gameServer/src/gameplay/Game.js
- gameServer/src/gameplay/Player.js
- gameServer/src/gameplay/arenaWorker/mod.js
- gameServer/src/gameplay/arenaWorker/updateCapturedArea.js
- gameServer/src/util/util.js
> feat(gs): Keep track of player scores

- gameServer/src/gameplay/Game.js
- gameServer/src/gameplay/Player.js
> fix(gs): Set lastUnpausedDirection for newly created players

- gameServer/src/gameplay/PlayerEventHistory.js
> fix(gs): Only undo events between the the positions where the player moved backwards

- gameServer/src/config.js
- gameServer/src/gameplay/Player.js
> feat: Better player position validation

- gameServer/src/gameplay/arenaWorker/PlayerBoundsTracker.js
- gameServer/src/gameplay/arenaWorker/mod.js
- gameServer/src/gameplay/arenaWorker/updateCapturedArea.js
> feat(gs): Update player bounds after filling areas

- gameServer/src/gameplay/Player.js
> fix(gs): Only allow killing players once

- gameServer/src/gameplay/Player.js
> fix: Kill both players when they hit each other head on

- gameServer/src/config.js
- gameServer/src/gameplay/Player.js
> fix(gs): Make sure clients receive correct skin color ids

- gameServer/src/gameplay/Player.js
- gameServer/src/gameplay/PlayerEventHistory.js
> fix(gs): Undo trail creation when the player moves back

- gameServer/src/WebSocketConnection.js
- gameServer/src/gameplay/Game.js
- gameServer/src/gameplay/Player.js
> feat(gs): End trail animation

- adminPanel/src/GameServer.js
- adminPanel/style.css
- serverManager/src/GameServer.js
> feat(admin,sm): Add official property to gameservers

- adminPanel/src/GameServer.js
- serverManager/src/GameServer.js
> feat(admin,gs): Add recommended property to gameservers

- gameServer/src/gameplay/Game.js
- gameServer/src/gameplay/Player.js
- gameServer/src/gameplay/arenaWorker/mod.js
> fix(gs): Trail ends on previous tile

- gameServer/src/WebSocketConnection.js
- gameServer/src/gameplay/Game.js
- gameServer/src/gameplay/Player.js
> feat(gs): Send all death stats

- gameServer/src/gameplay/Player.js
- gameServer/src/gameplay/PlayerEventHistory.js
> fix(gs): No points for running into the wall

- .github/workflows/release.yml
- client/index.html
- client/src/main.js
- client/static/style.css
- deno.json
- importmap.json
- scripts/buildClient.js
- scripts/dev.js
- serverManager/src/ServerManager.js
- serverManager/src/WebSocketManager.js
> feat(client): New server selection UI

- adminPanel/src/GameServer.js
- serverManager/src/GameServer.js
> feat(admin,sm): Support for disabling control socket for some servers

- gameServer/src/WebSocketConnection.js
I think this fixes #80 but we won't know until it's deployed
> fix(gs): Ignore ready state not open errors

- client/src/main.js
- serverManager/src/GameServer.js
- serverManager/src/ServerManager.js
> feat(client,sm): Auto select the recommended server

- client/src/main.js
> feat(client): Show player count in server selection

- client/index.html
> feat(client): Update title screen text

- client/index.html
- client/src/globals.js
- client/src/main.js
- client/src/network/serverSelection.js
> refactor(client): Move to es modules

- adminPanel/src/WebsocketManager.js
- gameServer/src/ControlSocketConnection.js
- gameServer/src/WebSocketManager.js
- gameServer/src/gameplay/Arena.js
- gameServer/src/gameplay/arenaWorker/getMinimapPart.js
- gameServer/src/gameplay/arenaWorker/mod.js
- importmap.json
- scripts/dev.js
- serverManager/src/GameServer.js
- serverManager/src/Main.js
- shared/RateLimitManager.js
> feat(gs): Lower rate limit when there are fewer than 5 connections

- client/src/main.js
> fix(client): fix WrappedWebSocket not being defined

- client/index.html
- client/leaderboards.html
- client/src/leaderboards.js
- client/static/leaderboards.css
- gameServer/src/Main.js
- gameServer/src/WebSocketManager.js
- gameServer/src/config.js
- gameServer/src/gameplay/Game.js
- gameServer/src/gameplay/Player.js
- importmap.json
- scripts/buildClient.js
- serverManager/src/GameServer.js
- serverManager/src/Leaderboard.js
- serverManager/src/LeaderboardGroup.js
- serverManager/src/LeaderboardManager.js
- serverManager/src/Main.js
- serverManager/src/ServerManager.js
- serverManager/src/WebSocketManager.js
> feat(client,gs,sm): Revive the global leaderboard

- scripts/downloadRelease.js
This should help towards fixing #116
> chore: Add logging to downloadRelease.js

- gameServer/src/gameplay/Game.js
- gameServer/src/gameplay/Player.js
> fix(gs): Broadcast by viewports

- client/leaderboards.html
- gameServer/src/gameplay/Player.js
> fix(gs): Use seconds for rankingFirst global leaderboard

- gameServer/src/ApplicationLoop.js
- gameServer/src/Main.js
- gameServer/src/gameplay/Game.js
- gameServer/src/gameplay/Player.js
> feat(gs): Limit max tick duration

- gameServer/src/gameplay/Game.js
- gameServer/src/gameplay/Player.js
Fixes seeing yourself as a red unnamed player for a short moment when spawning
> fix(gs): Send player info immediately

- gameServer/src/gameplay/Game.js
Continuation of #120, required #133 first
> fix(gs): Broadcast state by viewports

- client/src/main.js
- client/src/network/serverSelection.js
fixes #96 
Let me know if I've missed any edge cases here.
> fix(client): Add Keep selected server on refresh

- gameServer/src/Main.js
- gameServer/src/gameplay/Game.js
- gameServer/src/gameplay/Player.js
- gameServer/src/mainInstance.js
- scripts/dev.js
Adds a drawing gamemode which makes it impossible to kill players by hitting their trail.
Also adds an argument which can be used for future gamemodes
> feat(gs): Add drawing gamemode

- Dockerfile
Makes it easier to deploy the server
> chore: Create Dockerfile for linux server

- Dockerfile
> chore: Dockerfile fixes

- gameServer/src/Main.js
- gameServer/src/gameplay/Arena.js
- gameServer/src/gameplay/Game.js
- gameServer/src/gameplay/Player.js
- gameServer/src/gameplay/arenaWorker/mod.js
- gameServer/src/mainInstance.js
- gameServer/src/util/util.js
- scripts/dev.js
> feat(gs): Add arena gamemode

- client/flags.html
- client/src/main.js
- gameServer/src/WebSocketConnection.js
- gameServer/src/gameplay/Player.js
I'm fairly confident that this fixes #43
> fix(gs,client): Prevent 180 degree turn
